import { Project } from "./components/types";

export const home = [
  { title: "EP Fast", date: "2020" },
  { title: "Merlin Bird ID", date: "2020" },
  { title: "Data Archive for the BRAIN Initiative", date: "2020" },
  { title: "Story on a Page", date: "2020" },
];

export const project1: Project = {
  id: 1,
  title: "EP Fast",
  date: "2019",
  route: "epfast",
  subtitle: "Visualizing the Power Grid for Argonne National Lab",
  overview:
    "Electric Power Fast is a data dashboard created to visualize US power grid data in the event of significant grid disruption. Our team at RS21 connected with engineers at Argonne national Lab to improve their method of visualizing their data, which was not producing the insights it could. My role on this project was to team up with data scientists at our company and engineers at Argonne to understand the data, and make it Intuitive. I also provided UX and UI on the dashboard.",
  client: "RS21 for Argonne National Lab ",
  role: "UX Designer",
  tools: "Sketch",
  headerImage: "/epfast/header.png",
  homeImage: "/epfast/header.png",
  product: "Dashboard",
  likeImage: "/placeholder2.png",
  blocks: [
    { type: "heading", label: "Design Process", text: "", path: [""] },
    { type: "image", label: "", text: "", path: ["/epfast/1.png"] },
    { type: "heading", label: "Empathize", text: "", path: [""] },
    {
      type: "image",
      label: "Interviews",
      text: "I conducted interviews with members of the Argonne engineering team to understand the problem. I've selected some choice quotes from the engineers below.",
      path: ["/epfast/2.png"],
    },
    {
      type: "image",
      label: "Working with a Team",
      text: "I worked with a data scientist and front-end developer to understand the data and execute the designs.",
      path: ["/epfast/3.png"],
    },
    { type: "heading", label: "Define", text: "", path: [""] },
    {
      type: "image",
      label: "Value Proposition",
      text: "",
      path: ["/epfast/4.png"],
    },
    {
      type: "image",
      label: "Islanding, a Visualization Problem",
      text: "An Island is a section of the grid from or to which power cannot flow. Islands form when the grid is disrupted, and detecting them is critical to getting the grid back online. An island is composed of lines and nodes. Even at this small scale, this original visualization creates ambiguity as to which island contains which nodes. This only becomes a bigger problem as the data scales to include the whole US grid with its thousands of nodes and lines.",
      path: ["/epfast/5.png"],
    },
    {
      type: "image",
      label: "What Needs to be Visualized",
      text: "The engineers gave us CSV data of the following, which we were tasked with visualizing in a geospatial form.",
      path: ["/epfast/6.png"],
    },
    { type: "heading", label: "Research", text: "", path: [""] },
    {
      type: "image",
      label: "Reading Tufte",
      text: "I read two books on data visualization to better understand the problem.",
      path: ["/epfast/7.png"],
    },
    {
      type: "image",
      label: "Understanding the Grid",
      text: "",
      path: ["/epfast/8.png"],
    },

    { type: "heading", label: "Ideate", text: "", path: [""] },
    {
      type: "image",
      label: "Sketches",
      text: "Ideation for islanding involved exploring options for bounding the islands given different ambiguous cases. Shown below is a case where a single unconnected node is in the middle of a set of connect ones. Also shown is a sketch exploring menu placement.",
      path: ["/epfast/9.png"],
    },
    { type: "heading", label: "Design", text: "", path: [""] },
    {
      type: "image",
      label: "Islanding Breakthrough",
      text: "I worked with the team developer to come up with a visualization solution that involves using a Voronoi algorithm to closely envelop nodes, and using an interaction to clarify ambiguous nodes and lines.",
      path: ["/epfast/10.png"],
    },
    {
      type: "image",
      label: "Nodes / Lines",
      text: "I designed a visual system for types of nodes and lines aligning with data specifications. The generation lost nodes are brighter because those are more important for the engineers to see. This kind of visualization can be turned on and off depending on what needs to be visualized. Given the complexity of the data, we opted for very simple icons.",
      path: ["/epfast/11.png", "/epfast/12.png"],
    },
    { type: "heading", label: "Demos", text: "", path: [""] },
    {
      type: "video",
      label: "Islanding",
      text: "Users can click to see outlines of various grid islands",
      path: ["/epfast/islands.mp4"],
    },
    {
      type: "video",
      label: "Nodes",
      text: "Users can click Cluster nodes to get more information",
      path: ["/epfast/nodes.mp4"],
    },
    {
      type: "video",
      label: "Lines",
      text: "Lines show the directional flow of energy",
      path: ["/epfast/lines.mp4"],
    },
    {
      type: "video",
      label: "Scale",
      text: "When zooming out, the visualization turns into a heat map showing node density",
      path: ["/epfast/zoom_nodes.mp4"],
    },
    { type: "heading", label: "Feedback", text: "", path: [""] },
    {
      type: "paragraph",
      label: "Implementation Issues",
      text: "There were some issues with implementing the designs, particularly with different screen sizes. In response to this I decided to learn how to code responsive HTML and CSS in order to communicate how to implement designs more effectively.",
      path: [""],
    },
    {
      type: "paragraph",
      label: "Narrativizing Designs",
      text: "One piece of feedback from this project is that the dashboard loads with all the data showing at once. This was overwhelming for some during demos. We should have loaded the dashboard with the islanding visualization alone, and perhaps dropped in some tool tips to guide users to additional layers.",
      path: [""],
    },
  ],
};

export const project2: Project = {
  id: 0,
  title: "Data Archive for the BRAIN Initiative",
  date: "2023",
  route: "dabi",
  subtitle:
    "Product Management, Development & Design for a Neuro-physiology data analysis Toolkit",
  overview:
    "In This project I acted as designer, developer, and product manager for a brain data archive and nacent analysis tool. I was instrumental in pivoting the analysis product in a more successful direction and improving UX for the archive.",
  client: "Laboratory of NeuroImaging",
  role: "Designer / Developer / Product Manager",
  tools: "Figma, React, Flask, etc",
  headerImage: "/dabi/header2.png",
  homeImage: "/dabi/header2.png",
  product: "Analysis Tool",
  likeImage: "placeholder2.png",
  blocks: [
    { type: "heading", label: "Background", text: "", path: [""] },
    {
      type: "image",
      label: "DABI - an archive for iEEG data",
      text: "The Data Archive for the BRAIN Initiative is an archive whose purpose is to store human invasive electrophysiology data, in other words, data from brain surgeries or devices that involve electrodes.",
      path: ["/dabi/ieeg.jpeg"],
    },
    {
      type: "image",
      label: "The BRAIN Initiative",
      text: "The NIH BRAIN Initiative is our funder, and also supports an ecosystem of neuroscientists trying to unlock the secrets of the brain. As an archive, we're responsible for storing and making vaailble data from said ecosystem.",
      path: ["/dabi/bi.png"],
    },
    {
      type: "image",
      label: "LONI - MRI vs iEEG",
      text: "Our lab, the Laboratory of Neuroimaging, made it's name creating archives for MRI data. Since DABI, responsible for a different modality, was an interesting challenge.",
      path: ["/dabi/mri_eeg.png"],
    },
    {
      type: "image",
      label: "The promise of an analysis-driven archive",
      text: "Brain data archives inspire the promise of large-scale, multi-study analyses where one collets features, builds cohorts, and find patterns in data via statistical methods. The Lab had had success with this approach in the MRI World, so an attempt was made to do the same for iEEG data.",
      path: ["/dabi/analysis-driven.png"],
    },
    { type: "heading", label: "Design Process", text: "", path: [""] },
    { type: "image", label: "", text: "", path: ["/dabi/DABI_process.png"] },
    {
      type: "paragraph",
      label: "",
      text: "Note that aside from reasses, other process steps happened in tandem.",
      path: ["/dabi/DABI_process.png"],
    },
    { type: "heading", label: "Reasses", text: "", path: [""] },
    {
      type: "paragraph",
      label: "We Lost the Grant - 5 Problems",
      text: "My first month at the lab, we heard back that said attempt had failed. We lost our revewal. In the review response, and after internal team audits, we identified some issues.",
      path: [""],
    },
    {
      type: "image",
      label: "1. Design - Confusing User Experience",
      text: "The revieweers found the side confusing and difficult to use. The team had gotten this feedback before, which is why I was hired, but the problems were deeper than UX.",
      path: ["/dabi/provider_old.png", "/dabi/build_cohorts.png"],
    },
    {
      type: "image",
      label: "2. Science - Untenable Analysis",
      text: "MRI data is quite uniform and plentiful, leading to opportunities for large-scale analysis that simply isn't there for iEEG. I worked with researchers to produce this slide to express to leadership why we couldn't follow the familiar playbook here. ",
      path: ["/dabi/variability.png"],
    },
    {
      type: "image",
      label: "3. Engineering - Technical Difficulties",
      text: "The archive and analysis applications were quite buggy, and the reviewers noticed. Many interactions were buggy, and our backend was unreliable and slow.",
      path: ["/dabi/engineering.png"],
    },

    {
      type: "image",
      label: "4. People, Leadership and Coordination",
      text: "All of these issues ultimately arose from lack of leadership on the dev team. All devs were going in separate directions and not really commmunicating. The product followed suit.",
      path: ["/dabi/people.png"],
    },

    { type: "heading", label: "Research", text: "", path: [""] },
    {
      type: "paragraph",
      label: "Getting Smart",
      text: "Making tools in a technical field requires diving deep before making decisions.",
      path: ["/dabi/papers.png"],
    },
    {
      type: "image",
      label: "Reading Papers",
      text: "I spent several weeks reading survey papers of the types of analysis that were possible with the data that we had and checking my understanding with researchers at the lab.",
      path: ["/dabi/papers.png"],
    },
    {
      type: "image",
      label: "Comparative Analysis",
      text: "I suggested we do a systematic analysis of other archives to get product ideas and initiate potential collaborations. We did so, published the findings, and gleaned insights from the exercise.",
      path: ["/dabi/comparative.png"],
    },
    {
      type: "paragraph",
      label: "Recurring Researcher Interviews",
      text: "A researcher coleague and I made it a habit of speaking to users directly while handling data, and made sure to field and filter feature requests and ask about the problems they intend to solve. Many of the improvements identified below were initiated by these conversations.",
      path: ["/placeholder.png"],
    },
    { type: "heading", label: "Re-Design", text: "", path: [""] },

    {
      type: "paragraph",
      label: "Less But Better",
      text: "At times it's tempting to make technical products seem more complex than they need to be. Avoid this temtation.",
      path: ["/placeholder.png"],
    },
    {
      type: "image",
      label: "Simplifying Navigation",
      text: "We went from many different navigation systems to just one. No need to reinvent the sidebar.",
      path: ["/dabi/nav.png"],
    },
    {
      type: "image",
      label: "Design System",
      text: "I created a new design system for the application directly in code. We needed ship fast to resubmit our proposal, so the feedback loop between design and development needed to be quick.",
      path: [
        "/dabi/home.png",
        "/dabi/request.png",
        "/dabi/syncfiles.png",
        "/dabi/subjects.png",
      ],
    },

    { type: "heading", label: "Re-Invent", text: "", path: [""] },
    {
      type: "image",
      label: "Analysis: From Analogy to First Principles",
      text: "When it comes to analysis tools, what worked for MRI wouldn't work for iEEG. Here's the reasoning I used to pivot the vision, and what our prototypes looked like once we started building.",
      path: ["/dabi/var.png", "/dabi/group2.png", "/dabi/lab-to-lab.png"],
    },
    {
      type: "image",
      label:
        "Pivoting from large group analysis, to collaborative feature extraction",
      text: "Since cross-study big data was untenable (too much variability, not enough subjects), we decided to reocus features on lab-tp-lab collaboration, building tools for co-processing data, and leave the statistics up to others. Our thesis, after speaking with users, was that these data pipelines are still far from automated. The user story is two or three labs working together on a handful of cases.",
      path: ["/dabi/fp.png"],
    },
    {
      type: "image",
      label: "Limiting Variability Through Data Standards",
      text: "We worked with other BRAIN Initiative partners to create a data ingestion standard that doesn't unduly constrain researchers while still enabling analysis by controlling things like file type and folder structure (EEG, unlike MRI, has hundreds of file types). We are also making a plan for communicating standards for data collection and study design, so more interoperable data is collected.",
      path: ["/dabi/edit2_3.png"],
    },
    {
      type: "video",
      label: "From Statistics to Signal Processing",
      text: "THe new cohort building flow is aimed at granular control which is better for small-scale studies. We developed a node-based processing tool that allows for collaborative and sharable processing of these cohorts",
      path: [
        "/dabi/search_build_cohorts.mp4",
        "/dabi/pipeline_fix_slowed.mp4",
        "/dabi/share.mp4",
      ],
    },
    {
      type: "video",
      label: "From Cohorts to Collaboration",
      text: "The Google Docs of iEEG Analysis - Hearing that human discernment is still paramount here, we build an app for real-time researcher annotation using websockets, attemping to move analysis beyond the desktop-app age.",
      path: ["/dabi/sync2.mp4"],
    },
    { type: "heading", label: "Re-Structure", text: "", path: [""] },
    {
      type: "paragraph",
      label: "My boss resigned. I was made manager 2 months in.",
      text: "It's been a fun challenge.",
      path: ["/placeholder.png"],
    },
    {
      type: "image",
      label: "Choosing People, Building Systems",
      text: "I interviewed dozens of candidates and hired 5. I also had to let go some of the original team. Choosing good people and setting up systems where they can coordinate and be productive is critical.",
      path: ["/dabi/team.png"],
    },
    { type: "heading", label: "Re-Engineer", text: "", path: [""] },
    {
      type: "paragraph",
      label: "Design How it Works",
      text: "The engineering side of things was a big learning experience for me here. I mostly listened to the team, made decisions about the highest leverage things to fix, assigned, and contributed myself where I could. We improved the archive on the following technical metrics.",
      path: ["/placeholder.png"],
    },
    {
      type: "image",
      label: "Ecosystem, APIs, Optimization, Data",
      text: "",
      path: ["/dabi/re-eng.png"],
    },

    { type: "heading", label: "Future Plans", text: "", path: [""] },
    {
      type: "image",
      label: "Branching out from a solid base",
      text: "Our future plans involve more tool integrations, more modalities, and community outreach to encourage multi-study analysis. Only once you are doing one thing well, however, should you branch out. We have a lot of work to do on core functions still.",
      path: ["/dabi/Multi.png"],
    },
  ],
};

export const project3: Project = {
  id: 4,
  title: "Cornell Birding Apps",
  date: "2020",
  route: "merlin",
  subtitle: "Improving UX for Cornell Lab's Citizen Ornithology apps",
  overview:
    "This project improves two birdwatching apps. Merlin Bird ID is an app that allows users to Identify birds. eBird is an app that allows uses to log sightings for citizen science. I noticed, as a user of both, that this pair of apps could be combined to improve user experience. After reading some reviews, I realized that I was not alone in this thought. I had been wanting to try a mobile UX project, so I ventured out on a project to understand and optimize the experience of these apps. ",
  client: "Personal Project",
  role: "UX / UI Designer",
  tools: "Invision Studio",
  headerImage: "/merlin/header.png",
  homeImage: "/merlin/header.png",
  product: "App Design",
  likeImage: "/placeholder2.png",
  blocks: [
    { type: "heading", label: "Design Process", text: "", path: [""] },
    {
      type: "image",
      label: "",
      text: "",
      path: ["/merlin/1.png"],
    },

    { type: "heading", label: "Empathize", text: "", path: [""] },
    {
      type: "image",
      label: "Review Analysis",
      text: "Reviews can be largely broken up into two main pieces: feedback relating to the fact that there's no way to save the birds you've Identified in Merlin, and that relating to the eBird 'Trip' feature, a way to organize your logs, being confusing.",
      path: ["/merlin/2.png"],
    },
    {
      type: "image",
      label: "Field Tests and Interviews",
      text: "I went birdwatching with three friends each with a different level of birdwatching expertise. I had each of them download the app and use it on our trip. Afterwards, I interviewed them asking about their experience. I picked out the most relevant quotes below.",
      path: ["/merlin/3.png"],
    },
    { type: "heading", label: "Define", text: "", path: [""] },
    {
      type: "image",
      label: "Value Proposition",
      text: "",
      path: ["/merlin/4.png"],
    },
    {
      type: "image",
      label: "Simplifying Touchpoints",
      text: "The Cornell Lab provides two apps for features that many users want in one app. The process of Identifying and logging birds could be completed in many fewer steps.",
      path: ["/merlin/5.png"],
    },
    {
      type: "image",
      label: "Organizing Logs",
      text: "Many birders go on multi-day trips, so providing a way to track and save their checklists in groups would allow them to organize sightings and memories.",
      path: ["/merlin/6.png"],
    },
    {
      type: "image",
      label: "Elevating the Interface",
      text: "Using these tools should be an elevating experience that reflects what it's like to experience these animals in nature.",
      path: ["/merlin/7.png"],
    },
    { type: "heading", label: "Ideate", text: "", path: [""] },
    {
      type: "image",
      label: "Sketches",
      text: "Some sketches of interface configurations. I considered a couple different bottom bars with different features surfaces.",
      path: ["/merlin/8.png"],
    },
    { type: "heading", label: "UX Design", text: "", path: [""] },
    {
      type: "image",
      label: "Combining the Apps",
      text: "Highlighted problem screens can be removed if the apps are combined, representing a significant jump in experience.",
      path: ["/merlin/9.png"],
    },
    {
      type: "image",
      label: "Menu System",
      text: "Information hierarchy was added to the menu system, reflecting the interests of users, with features catering to each user type in the bottom bar. This persistent bar also adds more mobility throughout the app.",
      path: ["/merlin/10.png"],
    },
    {
      type: "image",
      label: "Checklists and Trips",
      text: "Trips were given a new interface that allows users to have more than one folder, and shows a visual of the birds in each checklist. The new design ads more organization that allows users to track and remember their birding experiences.",
      path: ["/merlin/11.png"],
    },
    { type: "heading", label: "UI Design", text: "", path: [""] },
    {
      type: "image",
      label: "Typography",
      text: "The typography for the project takes inspiration from classic birding guides, combined with clean minimalist mobile design.",
      path: ["/merlin/12.png"],
    },
    {
      type: "image",
      label: "Design System",
      text: "I created a design system using the same brief from the typography: make something that combines the texture of classic bird guides with the usability of modern app design.",
      path: ["/merlin/13.png"],
    },
    {
      type: "image",
      label: "UI Improvements",
      text: "UI improvements for  more visual and reflect the experience of reading a bird guide or that of going birding itself.",
      path: ["/merlin/14.png"],
    },
    {
      type: "video",
      label: "Breadcrumb System",
      text: "Breadcrumb system increases ability to edit Bird ID results without starting over.",
      path: ["/merlin/1.mp4"],
    },
    {
      type: "video",
      label: "Identifying a bird and adding it to a checklist",
      text: "Now that the two apps combined, the process of adding a bird is much easier.",
      path: ["/merlin/2.mp4"],
    },
    {
      type: "video",
      label: "Creating a new checklist",
      text: "New checklist flow with added visuals",
      path: ["/merlin/3.mp4"],
    },
    { type: "heading", label: "Feedback", text: "", path: [""] },
    {
      type: "image",
      label: "Improvements Tracked",
      text: "I circled back with The three individuals I interviewed and asked them to interact with clickable prototypes, saying out loud anything they felt was notable.",
      path: ["/merlin/15.png"],
    },
    {
      type: "image",
      label: "Tracking Birds You've Identified",
      text: "I decided to design two of the pieces of feedback that pertained to keeping track of bird data",
      path: ["/merlin/16.png"],
    },
    {
      type: "paragraph",
      label: "Next Steps",
      text: "Next steps on this project, were it to have continued, would include responding to some other pieces of feedback, including addressing slight confusion on the trip feature and potentially simplifying logging steps. This would probably require speaking with the scientists to see which parts of the data are essential.",
      path: [""],
    },
  ],
};

export const project4: Project = {
  id: 3,
  title: "Story On a Page",
  date: "2021",
  route: "fndr",
  subtitle: "Creating a Brand Dashboard for FNDR",
  overview:
    "FNDR (pronounced ‘Founder’) is a brand consultancy that works with Founders and CEOs to build brand narratives and value systems for their companies. We were big on close-knit in-person meetings where founders could feel safe about getting their ideas out there. Everything was going great...and then Covid hit. I took the initiative to propose a digital experience that solved some issues which arose when working in person was no longer an option.",
  client: "FNDR",
  role: "Product Designer / Developer / Illustrator",
  tools: "Figma,  React,  Prismic",
  headerImage: "/fndr/header.png",
  homeImage: "/fndr/header.png",
  product: "Narrative Dashboard",
  likeImage: "placeholder2.png",
  blocks: [
    { type: "heading", label: "Design Process", text: "", path: [""] },
    {
      type: "image",
      label: "",
      text: "",
      path: ["/fndr/1.png"],
    },
    { type: "heading", label: "Empathize", text: "", path: [""] },
    {
      type: "image",
      label: "What is FNDR?",
      text: "",
      path: ["/fndr/2.png"],
    },
    {
      type: "image",
      label: "FNDR's Covid Story: The Problem",
      text: "FNDR works directly with, you guessed it, Founders! The process consists of 4 meetings over the course of which  a ‘Core Narrative’ is conceived which goes on to define decisions on everything from hiring to product design. This project is about designing how that narrative shows up",
      path: ["/fndr/3.png", "/fndr/4.png"],
    },
    {
      type: "image",
      label: "Digitizing the Story on a Page",
      text: "FNDR normally gave clients a deck of about 100 slides to sum up our recommendations. One of these slides was the Story on a Page which used modular narrative cards (shown below)  to sum up the narrative. Before this project, it was never prominently featured, but I suggested that we make it a larger aspect of how we communicate what we offer which resulted in a digital experience that because the core way we present and deliver to clients.",
      path: ["/fndr/5.png"],
    },
    { type: "heading", label: "Define", text: "", path: [""] },
    {
      type: "image",
      label: "Value Proposition",
      text: "",
      path: ["/fndr/6.png"],
    },
    {
      type: "image",
      label: "Interviews / Personas",
      text: "I Interviewed that leadership team at the company and got to experience clients who where left wanting at the final meeting which often seemed scatted from a delivery standpoint. They wanted more closure.",
      path: ["/fndr/7.png"],
    },

    { type: "heading", label: "Ideate", text: "", path: [""] },
    {
      type: "image",
      label: "Feature Ideas",
      text: "",
      path: ["/fndr/8.png"],
    },
    { type: "heading", label: "Design", text: "", path: [""] },
    {
      type: "image",
      label: "System Design",
      text: "A simple diagram of the system touchpoints. Note we made an extra dashboard for James, the CEO to use as a sales tool.",
      path: ["/fndr/9.png"],
    },
    {
      type: "image",
      label: "Solving the Single Page",
      text: "I presented these two layout options to leadership and we went with the left. I felt that there were pros and cons with each, but ultimately we went with what solved the initial problem of closure: we didn't want just another slide deck with endless information, so one page it was.",
      path: ["/fndr/10.png"],
    },
    {
      type: "image",
      label: "Mapping Narrative Cards",
      text: "The dashboard was created so that different narrative card types could be arranged in a matrix of boxes per the needs of a particular client. Each represented an aspect of the brand narrative. Below is a selection of some narrative card types we defined.",
      path: ["/fndr/11.png"],
    },
    {
      type: "image",
      label: "Values and Branding",
      text: "I worked with the CCO to define a look and feel for the project. FNDR, as a company, strove to create a space where business leaders could free their minds from the normal day-to-day concerns of their companies and dream big. As such we wanted the visuals to reflect this feeling of endless possibility. I created a series of illustrations of a character 'The Founder' each associated a narrative card type to reflect this feeling of discovery.",
      path: ["/fndr/12.png", "/fndr/13.png"],
    },
    { type: "heading", label: "Develop", text: "", path: [""] },
    {
      type: "paragraph",
      label: "",
      text: "After going over wireframes with the team, I developed the project using NextJS, a React framework, with a CMS named Prismic for the backend. ",
      path: [""],
    },
    {
      type: "image",
      label: "Constructing the Backend",
      text: "",
      path: ["/fndr/14.png"],
    },
    {
      type: "image",
      label: "Coding the Frontend",
      text: "",
      path: ["/fndr/15.png"],
    },
    { type: "heading", label: "Demo", text: "", path: [""] },
    {
      type: "video",
      label: "Client Dashboard Example",
      text: "Note: I cannot give actual examples due to NDA restrictions",
      path: ["/fndr/client.mp4"],
    },
    {
      type: "video",
      label: "Sales Dashboard",
      text: "",
      path: ["/fndr/sales.mp4"],
    },
    { type: "heading", label: "Feedback", text: "", path: [""] },
    {
      type: "paragraph",
      label: "Positive Reaction from Clients",
      text: "Productizing the Story on a Page was successful as a sales tool, and helped give clients more closure on the process.",
      path: [""],
    },
    {
      type: "paragraph",
      label: "Need for a better backend interface",
      text: "The Decision to use Prismic as a backend ended up being quick, but not as intuitive as it should have been for strategists to use due to its limited interface options, especially when the product got more complex. Since I was the only developer at the company, and had no backend skills, I took this as an opportunity get familiar with Django, the python backend framework, in order to prepare myself if something like this problem comes up again.",
      path: [""],
    },
    {
      type: "paragraph",
      label: "Next Steps",
      text: "Working at FNDR inspired me to think about how these narrative affect the systems inside companies. I studied this for a year and made a project. Check out 'Smart Plant Factory' below!",
      path: [""],
    },
  ],
};

export const project5: Project = {
  id: 2,
  title: "Smart Plant Factory",
  date: "2022",
  route: "plants",
  subtitle: "Developing a framework for values-driven systemic design",
  overview:
    "This project asks the question: How does a company's values affect the overall strategy it follows? Can this relationship be designed intentionally? This project uses the example of a hypothetical vertical farming company to frame the problem. I used the book Smart Plant Factory to learn about vertical farming technology and consulted  several sources for insights on systemic reasoning & design. I created all the following diagrams to explore the relationship between four different values / business strategies and the plant factory itself.",
  client: "Personal",
  role: "Systemic Designer",
  tools: "",
  headerImage: "/plants/header.png",
  homeImage: "/plants/home.png",
  product: "System Strategy",
  likeImage: "placeholder2.png",
  blocks: [
    {
      type: "image",
      label: "What is Systemic Design",
      text: "",
      path: ["/plants/1.png"],
    },
    {
      type: "image",
      label: "Roadmap for this project",
      text: "",
      path: ["/plants/2.png"],
    },
    { type: "heading", label: "Defining Values", text: "", path: [""] },
    {
      type: "paragraph",
      label:
        "Small changes in the beginning lead to huge differences down the road",
      text: "There are a number of methods for defining values. Often they occur organically, arising out of the business model of the company. Defining values this way is fine, but it ultimately lets the complex forces of the market and culture dictate decisions. Setting aside time where the leadership team can construct and/or revise a strong central vision using information from experts, users, team members, other stakeholders and society at large can prepare an organization for tough decisions.",
      path: ["/plants/2.png"],
    },
    {
      type: "image",
      label: "Choosing a Mission",
      text: "For this exercise, I'm going to explore four different missions for a Smart Plant Factory, examining the potential second-order effects of each choice on the business and technology systems. Such a process could be used to think through value-creation or implementation.",
      path: ["/plants/3.png"],
    },
    { type: "heading", label: "Mapping Systems", text: "", path: [""] },
    {
      type: "image",
      label: "Creating the Gigamap",
      text: "To intervene in systems, one must first understand them. I created a map to get the whole system on a page so that one can visually see points of leverage, critical technologies, or important connections, phases, functions etc. This, where a systems thinking exercise might end, is only one step in a systemic design project.",
      path: ["/plants/4.png", "/plants/5.png", "/plants/6.png"],
    },
    { type: "heading", label: "Applying Values", text: "", path: [""] },
    {
      type: "image",
      label: "From Values to System Properties",
      text: "",
      path: ["/plants/7.png"],
    },
    {
      type: "image",
      label: "From System Properties to Investment",
      text: "",
      path: [
        "/plants/8.png",
        "/plants/9.png",
        "/plants/10.png",
        "/plants/11.png",
      ],
    },
    {
      type: "heading",
      label: "Contending with Complexity",
      text: "",
      path: [""],
    },
    {
      type: "image",
      label: "Complexity Styles",
      text: "Every organization has to deal with complexity. Doing so in an intentional manner that is consistent with company values helps manage the noise. Complexity styles are a way for values to inform decisions related to complexity. This concept is based on research by Chih-Chun Chen and Nathan Crilly where synthetic biologists were interviewed about their methods for dealing with the complexities of biology. Three main strategies were identified. They are as follows.",
      path: ["/plants/12.png"],
    },
    {
      type: "image",
      label: "From System Properties to Complexity Styles",
      text: "",
      path: [
        "/plants/13.png",
        "/plants/14.png",
        "/plants/15.png",
        "/plants/16.png",
      ],
    },
    {
      type: "image",
      label: "More Coming Soon",
      text: "This project is still a work in progress. I plan on returning with more systems techniques as I explore the topic.",
      path: [""],
    },
  ],
};

export const projects = [project2, project1, project5, project4, project3];
